### ISSUE TITLE
Best practice to make  VisualFrame support float descriptor type?

### ISSUE THREAD

**Issue by pangfumin** [ethz-asl/aslam_cv2#50]
Hi,
Thank you for sharing this high-quality work!
I want to modify the base class VisualFrame, which only supports binary descriptor for now,   to support float descriptor type(e.g. from SIFT or other detectors ). 
At first glance, I plan to make this class a  template, but I found many codes which use this class need to be modified due to this change.
Do you have some advice?
Thank you!
Best Wishes. Pang Fumin @ Beijing

**Comment by Emilio-90** [comment]
@pangfumin How did you make it work?
